"""empty message

Revision ID: 31e240e66e6e
Revises: 13a4cdeb847a
Create Date: 2022-11-11 17:16:08.570906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e240e66e6e'
down_revision = '13a4cdeb847a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('emai_contact', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('number_contact', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('name_contact', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name_contact')
    op.drop_column('user', 'number_contact')
    op.drop_column('user', 'emai_contact')
    # ### end Alembic commands ###
